---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - ../../defaults/main.yml
    - ../../vars/main.yml
  vars:
    deploy_ssh_keys: []
    deploy_user: deploy
  roles:
    - name: hardening
