---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Verify sshd config has PasswordAuthentication disabled
      ansible.builtin.command: grep "^PasswordAuthentication no" /etc/ssh/sshd_config
      changed_when: false

    - name: Verify sshd config has PermitRootLogin disabled
      ansible.builtin.command: grep "^PermitRootLogin no" /etc/ssh/sshd_config
      changed_when: false

    - name: Verify deploy user exists
      ansible.builtin.command: id deploy
      changed_when: false
