---
# Sysctl kernel hardening

- name: Disable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "{{ sysctl_ipv4_forwarding }}"
    sysctl_set: true
    state: present
    reload: true

- name: Disable ICMP redirects
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "0"
    sysctl_set: true
    state: present
    reload: true
  loop:
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects
    - net.ipv6.conf.all.accept_redirects
    - net.ipv6.conf.default.accept_redirects

- name: Disable source routing
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "0"
    sysctl_set: true
    state: present
    reload: true
  loop:
    - net.ipv4.conf.all.accept_source_route
    - net.ipv4.conf.default.accept_source_route

- name: Enable logging of martians
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: true
    state: present
    reload: true
  loop:
    - net.ipv4.conf.all.log_martians
    - net.ipv4.conf.default.log_martians

- name: Disable ICMP send redirects
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "0"
    sysctl_set: true
    state: present
    reload: true
  loop:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects

- name: Enable TCP SYN cookies
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: "1"
    sysctl_set: true
    state: present
    reload: true